# Argo CD Application: Cilium CNI
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeops
  sources:
    # Cilium Helm chart, values pulled from the git repo via the $values ref
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.14.5
      helm:
        valueFiles:
          - $values/cilium/base/values.yaml
    - repoURL: https://github.com/wbatchayon/kubeops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
